pipelines:
  branches:
    master:
    - step:
        name: Composer install
        caches:
        - composer
        script:
        - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"$MAGENTO_USERNAME\",\"password\":\"$MAGENTO_PASSWORD\"}}}" > auth.json
        - composer install --prefer-dist --optimize-autoloader
    - step:
        name: PHP CodeSniffer
        caches:
        - composer
        script:
        - composer install
        - php vendor/bin/phpcs --standard=PSR2 Helper/ Observer/
    - step:
        name: PHP Mess Detector
        caches:
        - composer
        script:
        - composer install
        - php vendor/bin/phpmd Helper/,Observer/ text cleancode,codesize,controversial,design,naming,unusedcode
    - step:
        name: PHP Copy/Paste Detector
        caches:
        - composer
        script:
        - composer install
        - php vendor/bin/phpcpd Helper/,Observer/